{% set name = "radical.utils" %}
{% set version = "1.6.5" %}
{% set sha256 = "2e85d65cb61e80b2c224c48c2e528723937dfcad0b150e2af1c216576e9e7c0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or win]


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - future
    - colorama
    - netifaces
    - setproctitle
    - regex
    - pyzmq
    - msgpack-python
    - pymongo
    - munch
    - wheel

test:
  imports:
    - radical.utils

about:
  home: https://github.com/radical-cybertools/radical.utils
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Shared code and tools for various RADICAL Projects (http://radical.rutgers.edu/)
  description: |
    This Python package contains shared code and tools for various Radical Group projects.
  dev_url: https://github.com/radical-cybertools/radical.utils

extra:
  recipe-maintainers:
    - andre-merzky
    - iparask
