{% set name = "radical.utils" %}
{% set version = "1.52.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radical_utils-{{ version }}.tar.gz
  sha256: 6ea6769a44fef77d623d9545f2efecdd696ad7740f0bea8d354e396088d6ff84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - colorama
    - msgpack-python
    - netifaces
    - ntplib
    - pyzmq
    - regex
    - setproctitle

test:
  imports:
    - radical.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://radical-cybertools.github.io/radical.utils/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Shared code and tools for various RADICAL-Cybertools projects
  description: |
    This Python package contains shared code and tools for various RADICAL-Cybertools projects.
  dev_url: https://github.com/radical-cybertools/radical.utils

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - xylar
