{% set name = "radical.utils" %}
{% set version = "1.22.0" %}
{% set sha256 = "89c4e5d624a5486217cfa7e1bd6b23b86dea2f9ca5f68e8a17d4acbed00754c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or py>39 or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - colorama
    - msgpack-python
    - netifaces
    - ntplib
    - pymongo <4
    - pyzmq
    - regex
    - setproctitle

test:
  imports:
    - radical.utils

about:
  home: https://github.com/radical-cybertools/radical.utils
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Shared code and tools for various RADICAL-Cybertools projects
  description: |
    This Python package contains shared code and tools for various RADICAL-Cybertools projects.
  dev_url: https://github.com/radical-cybertools/radical.utils

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
