travis:
  secure:
    BINSTAR_TOKEN: XG3FF/TRe1DH7U8vdNnEFBto0X+FLLPLWMBI3NkGaizXoyUg2wR+7yhOe93yFpxnZf65ZG3v2lKHfWb4UdigLS0IPLOiQNDw5TGind0OBvgcesFNJPJfkG5zJb9Jb0cCJxV/iQSP8od3igA/1m85z/RtdppXJMKxfal3ZdZ0x9C1AtrPo1EWZtHMSiux5HuCAGTK2NCtcWc1ocE23HHsf/OgWkl3yuVESGhDEf/jXITUSyUEcM3Dc46Q2q1fFnqsezgjIH8czcboCkVmwa8b4p3fLiCuX0qaJmvynO8bK7QFnXztRkzxefSGlu+sYgD09n/H2ZZZgYRUM5mbkb4SzNryWrMYiVg6EVEBzsAgLCjlAC1jE3PVOXRS2KH2e3HXOadjfORCUCu/xAIvW8GO3HveB1WFO0itfow3aDwx3xW9Q4H3vnDKiaKiEMiKzw/5pUF1d+Wxm8PdB/fHRqjldZGNqoPNvASasMwa6QR4uRDV7QX6IhO2dgehB3MHdCn/enV0JdJtW3WFjRwdIDmDCay5ilmQ0dc1cnQv1eo2YiFsdEJ/VwNkrmUo1nXQ0ZJGaM4KhMae8oVTSPkkWfwRSS2ZZRfGI7EtmAIABVjEn2JSF4DQyJfEQQPd+nVNF7VrG1AFK3Hbg56hCzqVmcZWEeHUl0l47YpB4j0ESq4OdQY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
